<?php
/**
 * @file
 * Code for the Eche core feature.
 */

include_once 'eche_core.features.inc';
include_once 'inc/eche_core.page.inc';
include_once 'inc/eche_core.selfassessment.page.inc';
include_once 'inc/eche_core.casestudy.page.inc';

/**
 * Implements hook_page_alter().
 */
function eche_core_page_alter(&$page) {
  if (drupal_is_front_page()) {

  }
}

/**
 * Implements hook_menu().
 */
function eche_core_menu() {
  $items['eche'] = [
    'title' => 'Eche',
    'page callback' => 'eche_core_home_page',
    // Should be accessible for everyone.
    'access callback' => TRUE,
    'file' => 'inc/eche_core_home_page.page.inc',
    'type' => MENU_CALLBACK,
    'weight' => 5,
  ];

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function eche_core_preprocess_page(&$variables) {
  $node = menu_get_object();
  if (isset($node->type) && $node->type == 'eche') {
    $variables['theme_hook_suggestions'][] = 'page__eche';
    unset($variables['bgpage']);
    $variables['bgpage'] = 'eche';
    $variables['hide_page_margin'] = TRUE;
    $variables['show_eche_title'] = TRUE;
  }

  $current_path = current_path();
  if (strpos($current_path, 'user/my-submissions') !== FALSE || strpos($current_path,
      'user/shared-with-me') !== FALSE
  ) {
    $variables['hide_page_margin'] = TRUE;
    $variables['show_eche_title'] = TRUE;
    $variables['theme_hook_suggestions'][] = 'page__eche';
    $variables['title'] = t('Self-assessment');
  }

  if ($current_path == 'eche') {
    $variables['theme_hook_suggestions'][] = 'page__eche_front';
  }
}
