<?php
/**
 * @file
 * Code for the Erasmus+ 30 year anniversary: Event feature.
 */

include_once 'erasmus_30_year_anniversary_event.features.inc';
include_once 'includes/helper.inc';

/**
 * Implements hook_views_pre_render().
 */
function erasmus_30_year_anniversary_event_views_pre_render(&$view) {
  if ($view->name == 'erasmus_30_year_anniversary_events' && $view->current_display == 'page_30year_events') {

    $filter = isset($view->exposed_raw_input['country']) ?
      $view->exposed_raw_input['country'] : NULL;

    if (isset($filter) && $filter !== 'All') {
      $html = _erasmus_30_year_anniversary_event_count_participants_per_country($view->result);
      $header_options = [
        'content' => $html,
        'format' => 'full_html',
        'empty' => 0,
      ];
      $view->add_item('default', 'header', 'views', 'area', $header_options);
    }
  }
}

/**
 * Implements hook_theme().
 */
function erasmus_30_year_anniversary_event_theme() {
  return array(
    'erasmus_30_year_anniversary_event_header' => array(
      'variables' => array(
        'countries' => NULL,
        'events' => NULL,
        'participants' => NULL,
      ),
      'template' => 'erasmus-30-year-anniversary-event-header',
      'path' => drupal_get_path('module', 'erasmus_30_year_anniversary_event') . '/templates',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function erasmus_30_year_anniversary_event_block_info() {
  $blocks['e30ya_event_global_header'] = array(
    'info' => t('Erasmus+ 30 year global event header'),
    'region' => 'sidebar_right',
    'cache' => DRUPAL_CACHE_GLOBAL,
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'events',
    'theme' => 'erasmus_30year_anniversary',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function erasmus_30_year_anniversary_event_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'e30ya_event_global_header':
      $block['content']
        = _erasmus_30_year_anniversary_event_retrieve_global_event_block_content();
      break;
  }

  return $block;
}

/**
 * Implements hook_form_ID_alter().
 */
function erasmus_30_year_anniversary_event_form_views_exposed_form_alter(&$vars) {
  if (isset($vars['country'])) {
    $vars['country']['#options']['All'] = t('All countries');
  }
}

/**
 * Implements hook_preprocess_node().
 */
function erasmus_30_year_anniversary_event_preprocess_node(&$vars) {
  if (isset($vars['view']->name)
      && $vars['view']->name == 'erasmus_30_year_anniversary_events') {
    $vars['city'] = $vars['field_30ya_city'][0]['value'];
    $vars['country'] = $vars['field_30ya_country'][0]['taxonomy_term']->name;
    $vars['expected_participants']['number'] = $vars['field_30ya_expected_participants'][0]['value'];
    $vars['expected_participants']['title'] = t('Expected participants');
    $vars['link']['title'] = $vars['field_30ya_link'][0]['title'];
    $vars['link']['url'] = $vars['field_30ya_link'][0]['url'];
    $vars['organiser']['title'] = $vars['field_30ya_link_organiser'][0]['title'];
    $vars['organiser']['url'] = $vars['field_30ya_link_organiser'][0]['url'];
    $vars['date'] = $vars['field_30ya_txt_date'][0]['value'];
    $vars['sector'] = $vars['field_30ya_sector'][0]['value'];
    $vars['intro'] = $vars['body'][0]['value'];
  }
}
