<?php
/**
 * @file
 * Code for the erasmus_30ya_core feature.
 */

/**
 * Implements hook_custom_theme().
 *
 * Switch to my theme when applicable.
 */
function erasmus_30ya_core_custom_theme() {
  $is_allowed = FALSE;

  $node = menu_get_object('node');
  $allowed_types = [
    'erasmus_30_year_anniversary_page',
    'erasmus_30_year_anniversary_pres',
    'erasmus_30_year_anniversary_stor',
    'erasmus_30ya_event',
    'erasmus_30_year_anniversary_part',
    'erasmus_30_year_anniversary_hero',
    'erasmus_30_year_anniversary_home',
  ];
  if (is_object($node) && isset($node->type)
      && in_array($node->type, $allowed_types)) {
    $is_allowed = TRUE;
  }

  $allowed_uris = [
    'events',
    'partners',
    'share-my-story',
    'press-releases',
    'discover-erasmusplus',
    'country-facts-sheets-infographics',
  ];
  $current_path = current_path();
  if (in_array($current_path, $allowed_uris)) {
    $is_allowed = TRUE;
  }
  // If you have more themes, update the code below.
  if ($is_allowed) {
    return 'erasmus_30year_anniversary';
  }
}

/**
 * Implements hook_context_load_alter().
 *
 * Unset context from other sites.
 */
function erasmus_30ya_core_context_load_alter(&$context) {
  switch ($context->name) {
    case 'site_wide';
      global $theme;
      if ($theme == 'erasmus_30year_anniversary') {
        $array_to_unset = [
          'om_maximenu-om-maximenu-1',
          'block-5',
        ];
        foreach ($array_to_unset as $unset) {
          unset($context->reactions['block']['blocks'][$unset]);
        }
      }
      break;

    case 'erasmus_30_years_anniversary_campaign_global':
      global $theme;
      if ($theme !== 'erasmus_30year_anniversary') {
        // Unset all the blocks for this context.
        unset($context->reactions['block']['blocks']);
      }
      break;

  }
}

/**
 * Implements hook_preprocess_node().
 */
function erasmus_30ya_core_preprocess_node(&$vars) {
  $allowed_views = [
    'erasmus_30_year_anniversary_events',
    'erasmus_30_year_anniversary_stories',
    'erasmus_30_year_anniversary_partners',
    'erasmus_30_year_anniversary_country_facts_sheets_infographics',
  ];
  if (isset($vars['view']->name)
      && in_array($vars['view']->name, $allowed_views)) {
    $vars['theme_hook_suggestions'][] = 'node__card';
  }
}

/**
 * Implements hook_menu().
 */
function erasmus_30ya_core_menu() {
  $items = array();

  $items['admin/settings/erasmus_30ya_core'] = array(
    'title' => 'Erasmus+ 30 year anniversary settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('erasmus_30ya_core_admin'),
    'file' => 'admin/erasmus_30ya_core.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function erasmus_30ya_core_block_info() {
  $blocks['e30ya_global_social_sharing'] = array(
    'info' => t('Erasmus+ 30 year global social sharing'),
    'region' => 'footer',
    'cache' => DRUPAL_CACHE_PER_PAGE,
    'status' => TRUE,
    'theme' => 'erasmus_30year_anniversary',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function erasmus_30ya_core_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'e30ya_global_social_sharing':
      $block['content']
        = _erasmus_30_year_anniversary_event_retrieve_global_social_sharing_content();
      break;
  }

  return $block;
}

/**
 * Returns the HTML for the social sharing block.
 */
function _erasmus_30_year_anniversary_event_retrieve_global_social_sharing_content() {
  return theme('erasmus_30_year_anniversary_global_sharing', [
    'hashtags' => variable_get('e30ya_hashtag', 'ErasmusPlus'),
    'title' => drupal_get_title(),
  ]
  );
}

/**
 * Implements hook_theme().
 */
function erasmus_30ya_core_theme() {
  return array(
    'erasmus_30_year_anniversary_global_sharing' => array(
      'variables' => array(
        'hashtags' => NULL,
        'title' => NULL,
      ),
      'template' => 'social-share',
      'path' => drupal_get_path('module', 'erasmus_30ya_core') . '/templates',
    ),
  );
}

/**
 * Implements hook_preprocess_block().
 */
function erasmus_30ya_core_preprocess_block(&$vars) {
  global $theme;
  if ($theme == 'erasmus_30year_anniversary'
      && $vars['block_html_id'] == 'block-menu-menu-erasmus-30') {
    global $language;
    $path = path_to_theme();
    $logo_path = $path . '/logo_' . $language->language . '.png';
    if (file_exists($logo_path)) {
      $vars['logo'] = '/' . $logo_path;
    }
    else {
      $vars['logo'] = '/' . $path . '/logo.png';
    }
  }
}
