<?php
/**
 * @file
 * Code for the erasmus_30ya_core feature.
 */

/**
 * Implements hook_custom_theme().
 *
 * Switch to my theme when applicable.
 */
function erasmus_30ya_core_custom_theme() {
  $is_allowed = FALSE;

  $node = menu_get_object('node');
  $allowed_types = [
    'erasmus_30_year_anniversary_page',
  ];
  if (is_object($node) && isset($node->type)
      && in_array($node->type, $allowed_types)) {
    $is_allowed = TRUE;
  }

  $allowed_uris = [
    'events',
    'partners',
    'share-my-story',
  ];
  $current_path = current_path();
  if (in_array($current_path, $allowed_uris)) {
    $is_allowed = TRUE;
  }
  // If you have more themes, update the code below.
  if ($is_allowed) {
    return 'erasmus_30year_anniversary';
  }
}

/**
 * Implements hook_context_load_alter().
 *
 * Unset context from other sites.
 */
function erasmus_30ya_core_context_load_alter(&$context) {
  switch ($context->name) {
    case 'site_wide';
      global $theme;
      if ($theme == 'erasmus_30year_anniversary') {
        $array_to_unset = [
          'om_maximenu-om-maximenu-1',
          'block-5',
        ];
        foreach ($array_to_unset as $unset) {
          unset($context->reactions['block']['blocks'][$unset]);
        }
      }
      break;
    case 'erasmus_30_years_anniversary_campaign_global':
      global $theme;
      if ($theme !== 'erasmus_30year_anniversary') {
        // Unset all the blocks for this context.
        unset($context->reactions['block']['blocks']);
      }
      break;
  }
}
