<?php
/**
 * @file
 * Code for the Erasmus+ 30 year anniversary: Hero feature.
 */

include_once 'erasmus_30_year_anniversary_hero.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function erasmus_30_year_anniversary_hero_preprocess_node(&$node) {
  global $theme;
  if ($node['type'] == 'erasmus_30_year_anniversary_hero'
    && $theme == 'erasmus_30year_anniversary') {

    switch ($node['elements']['#view_mode']) {
      case 'teaser':
        $srt_uri = $node['field_30ya_hero_video_srt'][$node['language']][0]['uri'];
        $srt_url = file_create_url($srt_uri);
        $vid_url = $node['field_30ya_hero_video'][0]['file']->uri;
        unset($node['content']['field_30ya_hero_video']);
        $node['content']['srt'] = $srt_url;
        $node['content']['srt_lang'] = $node['language'];
        $node['content']['vid'] = file_create_url($vid_url);
        $banner_uri = $node['field_30ya_hero_banner'][0]['uri'];
        $node['content']['banner_url']
          = image_style_url('erasmus_30_year_hero_bg', $banner_uri);
        $suggestions = $node['theme_hook_suggestions'];
        array_unshift($suggestions, 'node__erasmus_30_year_anniversary_hero__teaser');
        $node['theme_hook_suggestions'] = $suggestions;

        $currentUri = request_uri();
        $currentUri = ltrim($currentUri, '/');
        $share_link = url(NULL, array('absolute' => TRUE))
        . $currentUri . '%23slideid-' . $node['nid'];

        $vars['share_fb'] = l(t('Share on Facebook', '', ['fragment' => '#']));
        $hashTags = variable_get('e30ya_hashtag', 'ErasmusPlus');
        $vars['share_tw'] = l(t('Tweet'),
          'https://twitter.com/intent/tweet?text=' . $vars['title'] . '&hashtags=' . $hashTags . '&url=' . $share_link,
          ['attributes' => ['class' => 'twitter-share-button', 'target' => '_blank']]
        );

        break;

      case 'erasmus_30_year_hero_homepage':
        $banner_uri = $node['field_30ya_hero_banner'][0]['uri'];
        $node['content']['banner_url']
          = theme('image_style', [
            'path' => $banner_uri,
            'style_name' => ['erasmus_30_year_hero_small_hp'],
            'attributes' => ['alt' => $vars['title']],
          ]
          );

        $node['content']['node_url'] = $node['node_url'];

        $node['content']['moreLink'] = l(t('Read more'),
          '/anniversary/discover-erasmusplus#slideid=' . $vars['nid'],
          ['attributes' => ['class' => 'button button--primary button--small']]
        );

        $suggestions = $node['theme_hook_suggestions'];
        array_unshift($suggestions,
          'node__erasmus_30_year_anniversary_hero__teaser_homepage');
        $node['theme_hook_suggestions'] = $suggestions;
        break;
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function erasmus_30_year_anniversary_hero_preprocess_page(&$variables) {
  $allowed_uri = 'anniversary/discover-erasmusplus';
  $current_path = request_uri();

  if (strpos($current_path, $allowed_uri) !== FALSE) {
    drupal_add_css('//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css', 'external');
    drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js', 'external');
    drupal_add_js(drupal_get_path('module', 'erasmus_30_year_anniversary_hero')
      . '/js/erasmus_30_year_anniversary_hero.js');
    drupal_add_js(drupal_get_path('module', 'erasmus_30_year_anniversary_hero')
      . '/js/all_heroes_dropdown.js');
    drupal_add_js(drupal_get_path('module', 'erasmus_30_year_anniversary_hero')
      . '/js/social_hero.js');
    drupal_add_js(drupal_get_path('module', 'erasmus_30_year_anniversary_hero')
      . '/js/video_controls.js');

    $variables['theme_hook_suggestions'][] = 'page__discover_erasmusplus';
  }
}

/**
 * Implements hook_preprocess_html().
 */
function erasmus_30_year_anniversary_hero_preprocess_html(&$variables) {
  $allowed_uri = 'anniversary/discover-erasmusplus';
  $current_path = request_uri();
  if (strpos($current_path, $allowed_uri) !== FALSE) {
    $variables['classes_array'][] = 'discover-erasmus-plus';
  }
}
