<?php
/**
 * @file
 * ECHE date format definition.
 *
 * @see http://thinkshout.com/blog/2014/05/custom-date-formats-in-drupal/
 */

/**
 * Implements hook_date_formats().
 */
function eche_date_format_date_formats() {
  $formats = [];
  $formats[] = [
    'type' => 'ec_date_format',
    'format' => 'j F Y',
    'locales' => [],
  ];
  foreach ($formats as $format) {
    variable_set('date_format_' . $format['type'], $format['format']);
  }
  return [$formats];
}

/**
 * Implements hook_date_format_types().
 */
function eche_date_format_date_format_types() {
  return [
    'ec_date_format' => t('EC date format'),
  ];
}
