<?php
/**
 * @file
 * Code for the Erasmus+ 30 year anniversary: Homepage feature.
 */

include_once 'erasmus_30_year_anniversary_homepage.features.inc';

/**
 * Implements hook_preprocess_page().
 */
function erasmus_30_year_anniversary_homepage_preprocess_page(&$vars) {
  if (isset($vars['node'])
      && $vars['node']->type == 'erasmus_30_year_anniversary_home') {

    $body = $vars['node']->body[$vars['node']->language][0]['value'];
    $right = _erasmus_30_year_anniversary_story_get_html_random_stories();

    $vars['page']['sidebar_left'] = $body;
    $vars['page']['sidebar_right'] = $right;
  }
}
