<?php
/**
 * @file
 * Code for Erasmus+ 30 year anniversary: Country fact sheets & infographics.
 */

include_once 'erasmus_30_year_anniversary_country_fact_sheets_infographics.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function erasmus_30_year_anniversary_country_fact_sheets_infographics_preprocess_node(&$vars) {
  if (isset($vars['elements']['#view_mode'])
      && $vars['elements']['#view_mode'] == 'teaser'
      && $vars['type'] == 'erasmus_30_year_anniversary_fact') {
    unset($vars['date']);

    foreach ($vars['field_30ya_fact_sheets'][$vars['language']] as $fact_sheet) {
      $factSheet = l('',
        '',
        [
          'attributes' => [
            'title' => $fact_sheet['description'],
            'class' => 'button button--primary button--medium',
          ],
        ]
      );
      $vars['fact_links'][] = $factSheet;
    }
  }
}
