<?php
/**
 * @file
 * Code for the Erasmus+ 30 year anniversary: Story feature.
 */

include_once 'erasmus_30_year_anniversary_story.features.inc';

/**
 * Implements hook_block_info().
 */
function erasmus_30_year_anniversary_story_block_info() {
  $blocks['e30ya_story_block'] = array(
    'info' => t('Erasmus+ 30 year Monthly story'),
    'region' => 'content',
    'cache' => DRUPAL_CACHE_PER_PAGE,
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'stories/*',
    'theme' => 'erasmus_30year_anniversary',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function erasmus_30_year_anniversary_story_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'e30ya_story_block':
      $block['content']
        = _erasmus_30_year_anniversary_story_get_monthly_theme();
      break;
  }

  return $block;
}

/**
 * Retrieve the monthly stories block for month specified in url.
 */
function _erasmus_30_year_anniversary_story_get_monthly_theme() {
  $url = request_uri();
  $url = explode('/', request_uri());

  if (count($url) < 2) {
    return NULL;
  }

  $url = $url[2];
  if (strpos($url, '_') === FALSE) {
    return NULL;
  }

  $url = explode('_', $url);
  $month_url = $url[0];

  $var_name = 'e30ya_monthly_theme_' . drupal_strtolower($month_url);
  $current_theme_month = variable_get($var_name, NULL);

  if ($current_theme_month) {
    return views_embed_view('erasmus_30_year_anniversary_stories',
    'block_30year_anniversary_monthly_theme', $current_theme_month);
  }
}

/**
 * Retrieve the homepage HTML for the random stories.
 */
function erasmus_30_year_anniversary_story_get_html_random_stories() {
  $result = db_select('node', 'n')
    ->condition('type', 'erasmus_30_year_anniversary_stor')
    ->fields('n', ['nid'])
    ->range(0, 4)
    ->orderRandom()
    ->execute();
  $images = [];
  foreach ($result as $record) {
    $node = $record->nid;
    $node = node_load($node);
    $images[] = $node->field_image[LANGUAGE_NONE][0];
  }
  $counter = 1;
  $themed_images = [];
  foreach ($images as $image) {
    $url = $image['uri'];
    switch ($counter) {
      case '1':
        $themed_images[$counter]['url']
          = image_style_url('erasmus_30_year_story_small__280x280', $url);
        $themed_images[$counter]['alt'] = $image['alt'];
        break;

      case '2':
        $themed_images[$counter]['url']
          = image_style_url('erasmus_30_year_story_medium__300x300', $url);
        $themed_images[$counter]['alt'] = $image['alt'];
        break;

      case '3':
        $themed_images[$counter]['url']
          = image_style_url('erasmus_30_year_story_large__520x520', $url);
        $themed_images[$counter]['alt'] = $image['alt'];
        break;

      case '4':
        $themed_images[$counter]['url']
          = image_style_url('erasmus_30_year_story_huge__720x574', $url);
        $themed_images[$counter]['alt'] = $image['alt'];
        break;
    }
    $counter++;
  }
  return theme('erasmus_30_year_anniversary_random_stories',
    ['stories' => $themed_images]);
}

/**
 * Implements hook_theme().
 */
function erasmus_30_year_anniversary_story_theme() {
  return array(
    'erasmus_30_year_anniversary_random_stories' => array(
      'variables' => array(
        'stories' => NULL,
      ),
      'template' => 'erasmus-30-year-anniversary-random-stories',
      'path' => drupal_get_path('module', 'erasmus_30_year_anniversary_story') . '/templates',
    ),
  );
}

/**
 * Implements hook_preprocess_node().
 */
function erasmus_30_year_anniversary_story_preprocess_node(&$vars) {
  if (isset($vars['view']->name)
      && $vars['view']->name == 'erasmus_30_year_anniversary_stories') {

    $image = image_style_url('erasmus_30_year_story_card__370x210',
      $vars['field_image'][0]['uri']);
    $vars['image'] = $image;
    $vars['theme'] = $vars['field_e30ya_monthly_theme'][0]['taxonomy_term']->name;
    unset($vars['date']);
  }
  
  if (isset($vars['elements']['#view_mode'])
      && $vars['elements']['#view_mode'] == 'full'
      && $vars['type'] == 'erasmus_30_year_anniversary_stor') {
    unset($vars['content']['field_image']);
    unset($vars['content']['field_e30ya_monthly_theme']);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function erasmus_30_year_anniversary_story_preprocess_page(&$vars) {
  if (isset($vars['node'])
      && $vars['node']->type == 'erasmus_30_year_anniversary_stor') {

    $body
      = $vars['node']->field_e30ya_monthly_theme[LANGUAGE_NONE][0]['taxonomy_term']->name;
    $image = image_style_url('erasmus_30_year_story_large__520x520',
      $vars['node']->field_image[LANGUAGE_NONE][0]['uri']);
    $alt = $vars['node']->field_image[LANGUAGE_NONE][0]['alt'];
    $vars['page']['sidebar_left'] = $body;
    $vars['page']['sidebar_right'] = '<img src="' . $image . '" alt="' . $alt . '"/>';
  }
}
