<?php
/**
 * @file
 * Code for the Erasmus+ 30 year anniversary: File feature.
 */

include_once 'erasmus_30_year_anniversary_file.features.inc';

/**
 * Implements hook_views_pre_view().
 */
function erasmus_30_year_anniversary_file_views_pre_view(&$view, &$display_id, &$args) {
  $allowed_display_ids = [
    'block_e30ya_files_toolkit',
  ];
  if (in_array($display_id, $allowed_display_ids)) {
    $filters = $view->display_handler->get_option('filters');
    $term = taxonomy_get_term_by_name('e30ya_toolkit', 'erasmus_30_year_anniversary_file_tags');
    if (!empty($term) && isset($term->tid)) {
      $filters['field_e30ya_file_tag_tid']['value'][$term->tid]
        = $term->tid;
      $view->display_handler->override_option('filters', $filters);
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function erasmus_30_year_anniversary_file_preprocess_node(&$node) {
  global $theme;

  if ($node['type'] == 'erasmus_30_year_anniversary_file'
    && $theme == 'erasmus_30year_anniversary') {

    switch ($node['elements']['#view_mode']) {
      case 'teaser':
        $file_url = $node['field_e30ya_file'][0]['file']->uri;
        $size = format_size($node['field_e30ya_file'][0]['file']->filesize);
        $title = $node['title_field'][0]['value'];
        $node['content']['file'] = l(t('Download'),
          file_create_url($file_url),
          [
            'attributes' => [
              'title' => t('Download @title', ['@title' => $title]),
              'class' => 'button button--primary button--medium',
            ],
          ]
        );
        $node['content']['file_size'] = t('File size: @size', ['@size' => $size]);

        $suggestions = $node['theme_hook_suggestions'];
        array_unshift($suggestions, 'node__erasmus_30_year_anniversary_file__teaser');
        $node['theme_hook_suggestions'] = $suggestions;

        break;

      case 'full':
        drupal_goto('/anniversary/resources');

        break;
    }
  }
}
